version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/storage:/app/app/storage
      - ./backend/models:/app/models
    environment:
      - WHISPER_CPP_BIN=/app/models/whisper/main
      - WHISPER_CPP_MODEL=/app/models/whisper/ggml-base.en.bin
    restart: unless-stopped

  # Optional: static frontend served by vite preview (dev) or nginx (prod)
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run preview -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
