[project]
name = "rag-offline-backend"
version = "0.1.0"
description = "Offline-first RAG backend using FastAPI"
requires-python = ">=3.10"
authors = [{ name = "Your Name" }]
dependencies = []

[tool.black]
line-length = 100
target-version = ["py310"]


